import React from 'react'


export const languages =[
  {'value':'aa','name': 'Afar'},
  {'value':'ab','name': 'Abkhazian'},
  {'value':'af','name': 'Afrikaans'},
  {'value':'am','name': 'Amharic'},
  {'value':'ar','name': 'Arabic'},
  {'value':'as','name': 'Assamese'},
  {'value':'ay','name': 'Aymara'},
  {'value':'az','name': 'Azerbaijani'},
  {'value':'ba','name': 'Bashkir'},
  {'value':'be','name': 'Byelorussian'},
  {'value':'bg','name': 'Bulgarian'},
  {'value':'bh','name': 'Bihari'},
  {'value':'bi','name': 'Bislama'},
  {'value':'bn','name': 'Bengali'},
  {'value':'bo','name': 'Tibetan'},
  {'value':'br','name': 'Breton'},
  {'value':'ca','name': 'Catalan'},
  {'value':'co','name': 'Corsican'},
  {'value':'cs','name': 'Czech'},
  {'value':'cy','name': 'Welch'},
  {'value':'da','name': 'Danish'},
  {'value':'de','name': 'German'},
  {'value':'dz','name': 'Bhutani'},
  {'value':'el','name': 'Greek'},
  {'value':'en','name': 'English'},
  {'value':'eo','name': 'Esperanto'},
  {'value':'es','name': 'Spanish'},
  {'value':'et','name': 'Estonian'},
  {'value':'eu','name': 'Basque'},
  {'value':'fa','name': 'Persian'},
  {'value':'fi','name': 'Finnish'},
  {'value':'fj','name': 'Fiji'},
  {'value':'fo','name': 'Faeroese'},
  {'value':'fr','name': 'French'},
  {'value':'fy','name': 'Frisian'},
  {'value':'ga','name': 'Irish'},
  {'value':'gd','name': 'Scots Gaelic'},
  {'value':'gl','name': 'Galician'},
  {'value':'gn','name': 'Guarani'},
  {'value':'gu','name': 'Gujarati'},
  {'value':'ha','name': 'Hausa'},
  {'value':'hi','name': 'Hindi'},
  {'value':'he','name': 'Hebrew'},
  {'value':'hr','name': 'Croatian'},
  {'value':'hu','name': 'Hungarian'},
  {'value':'hy','name': 'Armenian'},
  {'value':'ia','name': 'Interlingua'},
  {'value':'id','name': 'Indonesian'},
  {'value':'ie','name': 'Interlingue'},
  {'value':'ik','name': 'Inupiak'},
  {'value':'in','name': 'former Indonesian'},
  {'value':'is','name': 'Icelandic'},
  {'value':'it','name': 'Italian'},
  {'value':'iu','name': 'Inuktitut (Eskimo)'},
  {'value':'iw','name': 'former Hebrew'},
  {'value':'ja','name': 'Japanese'},
  {'value':'ji','name': 'former Yiddish'},
  {'value':'jw','name': 'Javanese'},
  {'value':'ka','name': 'Georgian'},
  {'value':'kk','name': 'Kazakh'},
  {'value':'kl','name': 'Greenlandic'},
  {'value':'km','name': 'Cambodian'},
  {'value':'kn','name': 'Kannada'},
  {'value':'ko','name': 'Korean'},
  {'value':'ks','name': 'Kashmiri'},
  {'value':'ku','name': 'Kurdish'},
  {'value':'ky','name': 'Kirghiz'},
  {'value':'la','name': 'Latin'},
  {'value':'ln','name': 'Lingala'},
  {'value':'lo','name': 'Laothian'},
  {'value':'lt','name': 'Lithuanian'},
  {'value':'lv','name': 'Latvian, Lettish'},
  {'value':'mg','name': 'Malagasy'},
  {'value':'mi','name': 'Maori'},
  {'value':'mk','name': 'Macedonian'},
  {'value':'ml','name': 'Malayalam'},
  {'value':'mn','name': 'Mongolian'},
  {'value':'mo','name': 'Moldavian'},
  {'value':'mr','name': 'Marathi'},
  {'value':'ms','name': 'Malay'},
  {'value':'mt','name': 'Maltese'},
  {'value':'my','name': 'Burmese'},
  {'value':'na','name': 'Nauru'},
  {'value':'ne','name': 'Nepali'},
  {'value':'nl','name': 'Dutch'},
  {'value':'no','name': 'Norwegian'},
  {'value':'oc','name': 'Occitan'},
  {'value':'om','name': '(Afan) Oromo'},
  {'value':'or','name': 'Oriya'},
  {'value':'pa','name': 'Punjabi'},
  {'value':'pl','name': 'Polish'},
  {'value':'ps','name': 'Pashto, Pushto'},
  {'value':'pt','name': 'Portuguese'},
  {'value':'qu','name': 'Quechua'},
  {'value':'rm','name': 'Rhaeto-Romance'},
  {'value':'rn','name': 'Kirundi'},
  {'value':'ro','name': 'Romanian'},
  {'value':'ru','name': 'Russian'},
  {'value':'rw','name': 'Kinyarwanda'},
  {'value':'sa','name': 'Sanskrit'},
  {'value':'sd','name': 'Sindhi'},
  {'value':'sg','name': 'Sangro'},
  {'value':'sh','name': 'Serbo-Croatian'},
  {'value':'si','name': 'Singhalese'},
  {'value':'sk','name': 'Slovak'},
  {'value':'sl','name': 'Slovenian'},
  {'value':'sm','name': 'Samoan'},
  {'value':'sn','name': 'Shona'},
  {'value':'so','name': 'Somali'},
  {'value':'sq','name': 'Albanian'},
  {'value':'sr','name': 'Serbian'},
  {'value':'ss','name': 'Siswati'},
  {'value':'st','name': 'Sesotho'},
  {'value':'su','name': 'Sudanese'},
  {'value':'sv','name': 'Swedish'},
  {'value':'sw','name': 'Swahili'},
  {'value':'ta','name': 'Tamil'},
  {'value':'te','name': 'Tegulu'},
  {'value':'tg','name': 'Tajik'},
  {'value':'th','name': 'Thai'},
  {'value':'ti','name': 'Tigrinya'},
  {'value':'tk','name': 'Turkmen'},
  {'value':'tl','name': 'Tagalog'},
  {'value':'tn','name': 'Setswana'},
  {'value':'to','name': 'Tonga'},
  {'value':'tr','name': 'Turkish'},
  {'value':'ts','name': 'Tsonga'},
  {'value':'tt','name': 'Tatar'},
  {'value':'tw','name': 'Twi'},
  {'value':'ug','name': 'Uigur'},
  {'value':'uk','name': 'Ukrainian'},
  {'value':'ur','name': 'Urdu'},
  {'value':'uz','name': 'Uzbek'},
  {'value':'vi','name': 'Vietnamese'},
  {'value':'vo','name': 'Volapuk'},
  {'value':'wo','name': 'Wolof'},
  {'value':'xh','name': 'Xhosa'},
  {'value':'yi','name': 'Yiddish'},
  {'value':'yo','name': 'Yoruba'},
  {'value':'za','name': 'Zhuang'},
  {'value':'zh','name': 'Chinese'},
  {'value':'zu','name': 'Zulu'}
]


export default function languageSelector ({inputHandler, value}) {
  const lgOpt = [
    <option key='-1' />,
    ...languages.map((language, i) => (<option key={i} value={language.value}>{language.name}</option>))
  ]

  return (
    <select name='language' onChange={inputHandler} value={value}>
      {lgOpt}
    </select>
  )
}